spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    ddl-auto: none
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
tenants:
  datasources:
    clinica0001:
      url: jdbc:postgresql://localhost:5432/evoclinica?currentSchema=clinica0001
      driverClassName: org.postgresql.Driver
      username: evoclinica
      #password: 
      maximum-pool-size: 3
      pool-name: Hikari-clinica0001
    clinica0002:
      url: jdbc:postgresql://localhost:5432/evoclinica?currentSchema=clinica0002
      driverClassName: org.postgresql.Driver
      username: evoclinica
      #password: 
      maximum-pool-size: 3
      pool-name: Hikari-clinica0002