spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    ddl-auto: none
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
tenants:
  datasources:
    clinica0001:
      url: jdbc:h2:tcp://localhost:9092/~/.evopharma/evoclinica;SCHEMA=clinica0001;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      driverClassName: org.h2.Driver
      username: sa
      password: 
      minimum-pool-size: 1
      maximum-pool-size: 3
      pool-name: Hikari-clinica0001
      schema: clinica0001
      alias: dermatologianow
    clinica0002:
      url: jdbc:h2:tcp://localhost:9092/~/.evopharma/evoclinica;SCHEMA=clinica0002;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      driverClassName: org.h2.Driver
      username: sa
      password: 
      minimum-pool-size: 1
      maximum-pool-size: 3
      pool-name: Hikari-clinica0002
      schema: clinica0002
      alias: clinicadamulher
    clinica0003:
      url: jdbc:h2:tcp://localhost:9092/~/.evopharma/evoclinica;SCHEMA=clinica0003;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      driverClassName: org.h2.Driver
      username: sa
      password: 
      minimum-pool-size: 1
      maximum-pool-size: 3
      pool-name: Hikari-clinica0003
      schema: clinica0003
      alias: clinicadalua